CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id   INTEGER PRIMARY KEY,
    mpa_name VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    VARCHAR(255) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date timestamp,
    duration     INTEGER      NOT NULL,
    mpa_id       INTEGER      REFERENCES mpa (mpa_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS users
(
    user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    login         VARCHAR(255) NOT NULL,
    name          VARCHAR(255),
    birthday_date timestamp
);

CREATE TABLE IF NOT EXISTS liked_film_user
(
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre
(
    genre_id   INTEGER PRIMARY KEY,
    genre_name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id      INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id    INTEGER NOT NULL,
    is_confirmed BOOLEAN NOT NULL,
    PRIMARY KEY (user_id, friend_id)
);